// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3sVf2u3BcXPd02jzGJldGgHLstitmnyE',
    appId: '1:249676996876:web:6a6ef2b90e1cd1d10b2929',
    messagingSenderId: '249676996876',
    projectId: 'orders-dev-73a50',
    authDomain: 'orders-dev-73a50.firebaseapp.com',
    storageBucket: 'orders-dev-73a50.appspot.com',
    measurementId: 'G-2G2EHKQRKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn8liwXS5JTRWH-hiCMjWb7cPFEmOlnkY',
    appId: '1:249676996876:android:475597f0b5a649300b2929',
    messagingSenderId: '249676996876',
    projectId: 'orders-dev-73a50',
    storageBucket: 'orders-dev-73a50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLsjqxeyavwp7503WJJUippGx0QUM_KUs',
    appId: '1:249676996876:ios:ad58166f7c4fbc060b2929',
    messagingSenderId: '249676996876',
    projectId: 'orders-dev-73a50',
    storageBucket: 'orders-dev-73a50.appspot.com',
    iosClientId: '249676996876-89nncj26v0eek1gc68kb2o5slele41gh.apps.googleusercontent.com',
    iosBundleId: 'com.example.ordersDev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLsjqxeyavwp7503WJJUippGx0QUM_KUs',
    appId: '1:249676996876:ios:ad58166f7c4fbc060b2929',
    messagingSenderId: '249676996876',
    projectId: 'orders-dev-73a50',
    storageBucket: 'orders-dev-73a50.appspot.com',
    iosClientId: '249676996876-89nncj26v0eek1gc68kb2o5slele41gh.apps.googleusercontent.com',
    iosBundleId: 'com.example.ordersDev',
  );
}
